server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hemooffice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tgw123456
    driver-class-name: com.mysql.cj.jdbc.Driver
activiti:
  database-schema-update: true
  history-level: full
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    callSettersOnNulls: true
#日志配置
logging:
  config: classpath:logback-spring.xml