server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hemooffice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: tgw123456
    driver-class-name: com.mysql.cj.jdbc.Driver
